version: "3.3"
services:
  app:
    build: .
    command: python ./register-service/register.py
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    expose:
      - "8081"
    links:
      - db
    depends_on:
      - db
    networks:
      - register-network

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=users

    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro

    ports:
      - "27018:27017"
    expose:
      - "27017"
    networks:
      - register-network


networks:
  register-network:
    name: register-network
